#!/usr/bin/env python3
"""
GRC Compliance Report Generator for btrpa-scan
Parses JSONL scan data and generates risk-scored audit report
"""

import json
import sys
import argparse
from datetime import datetime
from collections import defaultdict
import statistics

SUSPICIOUS_KEYWORDS = [
    'hidden', 'cam', 'mic', 'spy', 'tracker', 'record', 'wiretap', 'eavesdrop',
    'audio', 'video', 'surveillance', 'nanny', 'baby', 'pet'
]

SEVERITY_ORDER = {'CRITICAL': 0, 'HIGH': 1, 'MEDIUM': 2, 'LOW': 3}

def parse_scan_data(jsonl_file):
    """Parse btrpa-scan JSONL output into device records."""
    devices = defaultdict(list)
    
    with open(jsonl_file, 'r') as f:
        for line_num, line in enumerate(f, 1):
            try:
                if not line.strip(): continue
                data = json.loads(line.strip())
                mac = data.get('address', 'unknown').upper()
                rssi = data.get('rssi', -100)
                name = data.get('name', 'Unknown')
                if name is None: name = "Unknown"
                name = name.lower()
                
                devices[mac].append({
                    'rssi': rssi,
                    'name': name,
                    'tx_power': data.get('tx_power', 0),
                    'timestamp': data.get('timestamp', 'unknown'),
                    'lat': data.get('latitude'),
                    'lon': data.get('longitude')
                })
            except json.JSONDecodeError as e:
                print(f"Warning: Invalid JSON on line {line_num}: {e}", file=sys.stderr)
    
    processed = []
    for mac, readings in devices.items():
        if not readings: continue

        avg_rssi = statistics.mean(r['rssi'] for r in readings)
        max_rssi = max(r['rssi'] for r in readings)
        strongest_reading = max(readings, key=lambda r: r['rssi'])
        
        device_name = "Unknown"
        for r in readings:
            if r['name'] and r['name'] != "unknown":
                device_name = r['name']
                break

        risk_level = 'LOW'
        findings = []
        
        if max_rssi >= -50:
            risk_level = 'HIGH'
            findings.append('Very close proximity (RSSI ≥ -50)')
        elif max_rssi >= -65:
            risk_level = 'MEDIUM'
            findings.append('Close proximity (RSSI ≥ -65)')
        
        if any(keyword in device_name for keyword in SUSPICIOUS_KEYWORDS):
            risk_level = 'CRITICAL'
            findings.append(f'Suspicious device name: "{device_name}"')
        
        processed.append({
            'mac': mac,
            'name': device_name.title(),
            'avg_rssi': round(avg_rssi, 1),
            'max_rssi': max_rssi,
            'risk_level': risk_level,
            'findings': '; '.join(findings),
            'best_gps': f"{strongest_reading['lat']}, {strongest_reading['lon']}" if strongest_reading.get('lat') else 'No GPS',
            'detections': len(readings)
        })
    
    return sorted(processed, key=lambda d: SEVERITY_ORDER[d['risk_level']])

def generate_report(devices, output_file='audit_report.md'):
    """Generate Markdown audit report."""
    report = f"""# Wireless Airspace Audit Report
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Generated by:** btrpa-report.py (GRC Enhancement)
**NIST Reference:** SP 800-121 Rev 2 (Bluetooth Security)

## Executive Summary
A wireless spectrum analysis was conducted to identify unauthorized Bluetooth Low Energy (BLE) assets.
A total of **{len(devices)} unique devices** were detected.

**Risk Summary:**
"""

    risk_counts = defaultdict(int)
    for device in devices:
        risk_counts[device['risk_level']] += 1
    
    for level in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']:
        count = risk_counts[level]
        if count > 0:
            report += f"- **{level}:** {count} devices\n"

    report += f"""
## Risk Analysis

| Risk Level | MAC Address | Device Name | Max RSSI | Findings | Detections |
|------------|-------------|-------------|----------|----------|------------|
"""
    
    for device in devices:
        report += f"| **{device['risk_level']}** | `{device['mac']}` | {device['name']} | {device['max_rssi']} dBm | {device['findings']} | {device['detections']} |\n"
    
    with open(output_file, 'w') as f:
        f.write(report)
    
    print(f"✅ Audit report generated: {output_file}")
    return risk_counts

def main():
    parser = argparse.ArgumentParser(description="GRC Compliance Report Generator")
    parser.add_argument("input_file", help="JSONL file from btrpa-scan")
    parser.add_argument("-o", "--output", default="audit_report.md", help="Output report file")
    
    args = parser.parse_args()
    
    if not args.input_file.endswith('.jsonl'):
        print("❌ Input must be a .jsonl file", file=sys.stderr)
        sys.exit(1)
    
    devices = parse_scan_data(args.input_file)
    risk_counts = generate_report(devices, args.output)
    
    print(f"📊 Processed {len(devices)} unique devices")
    sorted_risks = {k: risk_counts[k] for k in ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] if risk_counts[k] > 0}
    print(f"📈 Risk distribution: {sorted_risks}")

if __name__ == "__main__":
    main()
